disabled_rules:
  - line_length
  - trailing_whitespace
  - identifier_name

opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional

excluded:
  - .build
  - .swiftpm

warning_threshold: 10
